######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 12 18:56:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyBrowser.h
FORMS += MyBrowser.ui
SOURCES += main.cpp MyBrowser.cpp

include(pro.conf)